services:
    glassfish:
        build: ./
        ports:
          - "8090:8080"
    proxy:
      image: nginx
      ports:
        - 80:80
      volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - glassfish